# Generated by Django 5.0.3 on 2024-08-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(choices=[('Leisure', 'Leisure'), ('Educational', 'Educational'), ('Historical', 'Historical'), ('Diner', 'Diner')], default='Leisure', max_length=100)),
                ('category2', models.CharField(blank=True, choices=[('Leisure', 'Leisure'), ('Educational', 'Educational'), ('Historical', 'Historical'), ('Diner', 'Diner')], max_length=100, null=True)),
                ('category3', models.CharField(blank=True, choices=[('Leisure', 'Leisure'), ('Educational', 'Educational'), ('Historical', 'Historical'), ('Diner', 'Diner')], max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('timeclose', models.CharField(blank=True, max_length=20, null=True)),
                ('cost', models.CharField(blank=True, choices=[('0', '0'), ('1-200', '1-200'), ('201-500', '201-500'), ('501+', '501+')], max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='media')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media')),
                ('promo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('announcement', models.CharField(blank=True, max_length=5000, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('approval', models.BooleanField(blank=True, default=False, null=True)),
                ('map', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
