# Generated by Django 5.0.3 on 2024-08-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_populate_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.RemoveField(
            model_name='business',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='business',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='business',
            name='photos',
        ),
        migrations.AddField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(related_name='businesses', to='business.category'),
        ),
    ]
