# Generated by Django 5.0.3 on 2024-08-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_media_remove_business_photo_business_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='business.media'),
        ),
    ]
