# Generated by Django 5.0.3 on 2024-08-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_business_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='photo',
            new_name='photos',
        ),
    ]
