# Generated by Django 5.1.2 on 2024-11-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_business_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Temporarily Closed', 'Temporarily Closed'), ('For Renovation', 'For Renovation')], max_length=100, null=True),
        ),
    ]
