# Generated by Django 5.1.2 on 2024-11-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_business_lat_business_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True),
        ),
    ]
