# Generated by Django 5.1.2 on 2024-11-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_business_lat_alter_business_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
    ]
