# Generated by Django 5.1 on 2024-11-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
