# Generated by Django 5.0.3 on 2024-11-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='approval',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Soon to Open', 'Soon to Open'), ('Closed', 'Closed'), ('Temporarily Closed', 'Temporarily Closed'), ('For Renovation', 'For Renovation')], max_length=100, null=True),
        ),
    ]
