# Generated by Django 5.0.3 on 2024-08-26 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('favorites', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('Leisure', 'Leisure'), ('Educational', 'Educational'), ('Historical', 'Historical'), ('Diner', 'Diner')], default='Leisure', max_length=100)),
                ('category2', models.CharField(blank=True, choices=[('Leisure', 'Leisure'), ('Educational', 'Educational'), ('Historical', 'Historical'), ('Diner', 'Diner')], max_length=100, null=True)),
                ('category3', models.CharField(blank=True, choices=[('Leisure', 'Leisure'), ('Educational', 'Educational'), ('Historical', 'Historical'), ('Diner', 'Diner')], max_length=100, null=True)),
                ('time', models.CharField(max_length=20)),
                ('timeclose', models.CharField(max_length=20)),
                ('cost', models.CharField(blank=True, choices=[('0', '0'), ('1-200', '1-200'), ('201-500', '201-500'), ('501+', '501+')], max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='media')),
                ('thumbnail', models.ImageField(upload_to='media')),
                ('archived', models.BooleanField(default=False)),
                ('map', models.CharField(blank=True, max_length=2000, null=True)),
                ('promos', models.ImageField(blank=True, null=True, upload_to='media')),
                ('announcement', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.JSONField(default=list)),
                ('times', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('place_ids', models.JSONField(default=list)),
                ('types', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_itinerary', to=settings.AUTH_USER_MODEL)),
                ('itinerary_state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_itinerary', to='website.itinerarystate')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('businesses', models.ManyToManyField(to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('places', models.ManyToManyField(to='website.place')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.normaluser')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.place')),
            ],
            options={
                'unique_together': {('user', 'place', 'business')},
            },
        ),
    ]
