# Generated by Django 5.0.3 on 2024-08-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='category',
        ),
        migrations.RemoveField(
            model_name='place',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='place',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='place',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='place',
            name='photo',
        ),
        migrations.AddField(
            model_name='place',
            name='categories',
            field=models.ManyToManyField(related_name='places', to='website.category'),
        ),
        migrations.AddField(
            model_name='place',
            name='photo',
            field=models.ManyToManyField(blank=True, to='website.media'),
        ),
    ]
