# Generated by Django 5.0.3 on 2024-08-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    def populate_categories(apps, schema_editor):
        Category = apps.get_model('website', 'Category')
        categories = ['Leisure', 'Educational', 'Historical', 'Diner']
        for category in categories:
            Category.objects.create(name=category)

    dependencies = [
        ('website', '0002_category_media_remove_place_category_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_categories),
    ]
