# Generated by Django 5.0.3 on 2024-08-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_itinerarystate_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarystate',
            name='budget',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='itinerarystate',
            name='text',
            field=models.JSONField(default=list),
        ),
    ]
