# Generated by Django 5.1 on 2024-10-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_rating_content_type_remove_rating_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarystate',
            name='start_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
