# Generated by Django 5.1.2 on 2024-11-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_normaluser_email_alter_normaluser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='user',
        ),
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Temporarily Closed', 'Temporarily Closed'), ('For Renovation', 'For Renovation')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
