# Generated by Django 5.0.3 on 2024-11-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='businessid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
