# Generated by Django 5.1 on 2024-11-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_place_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='businessid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
