# Generated by Django 5.0.3 on 2024-03-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.IntegerField()),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(default='Leisure', max_length=100)),
                ('category2', models.CharField(blank=True, max_length=100, null=True)),
                ('category3', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('timeclose', models.CharField(blank=True, max_length=20, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('costmax', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='media')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media')),
                ('promo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('annoncement', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
