# Generated by Django 5.0.3 on 2024-08-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
    ]
