# Generated by Django 5.0.3 on 2024-04-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_refid'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(blank=True, default='Leisure', max_length=100, null=True),
        ),
    ]
