# Generated by Django 5.0.3 on 2024-08-29 02:22

from django.db import migrations


def populate_categories(apps, schema_editor):
    Category = apps.get_model('business', 'Category')
    categories = ['Leisure', 'Educational', 'Historical', 'Diner']
    for category in categories:
        Category.objects.create(name=category)

class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_category_remove_business_category_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_categories),
    ]