# Generated by Django 5.0.3 on 2024-08-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_populate_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='photo',
        ),
        migrations.AddField(
            model_name='business',
            name='photo',
            field=models.ManyToManyField(blank=True, to='business.media'),
        ),
    ]
