# Generated by Django 5.0.3 on 2024-04-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_business_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='approval',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
