# Generated by Django 5.0.3 on 2024-04-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_business_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(blank=True, default='Leisure', max_length=100, null=True)),
                ('category2', models.CharField(blank=True, max_length=100, null=True)),
                ('category3', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('timeclose', models.CharField(blank=True, max_length=20, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('costmax', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='media')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media')),
                ('promo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('annoncement', models.CharField(blank=True, max_length=5000, null=True)),
                ('approval', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='annoncement',
        ),
        migrations.RemoveField(
            model_name='business',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.RemoveField(
            model_name='business',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='business',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='business',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='business',
            name='costmax',
        ),
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='location',
        ),
        migrations.RemoveField(
            model_name='business',
            name='name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='business',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='business',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='business',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='business',
            name='time',
        ),
        migrations.RemoveField(
            model_name='business',
            name='timeclose',
        ),
    ]
