# Generated by Django 5.1 on 2024-10-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_rating'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_business_name',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='place',
            new_name='business',
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_business_name'),
        ),
    ]
