# Generated by Django 5.0.3 on 2024-04-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_businessdetails_remove_business_annoncement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='approval',
        ),
        migrations.AddField(
            model_name='business',
            name='approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
