# Generated by Django 5.1.2 on 2024-11-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_rating_unique_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Temporarily Closed', 'Temporarily Closed'), ('For Renovation', 'For Renovation')], max_length=100, null=True),
        ),
    ]
