# Generated by Django 5.0.3 on 2024-04-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_businessdetails_approval_business_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdetails',
            old_name='annoncement',
            new_name='announcement',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='costmax',
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='category',
            field=models.CharField(choices=[('Leisure', 'Leisure'), ('Educational', 'Educational'), ('Historical', 'Historical'), ('Diner', 'Diner')], default='Leisure', max_length=100),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='category2',
            field=models.CharField(blank=True, choices=[('Leisure', 'Leisure'), ('Educational', 'Educational'), ('Historical', 'Historical'), ('Diner', 'Diner')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='category3',
            field=models.CharField(blank=True, choices=[('Leisure', 'Leisure'), ('Educational', 'Educational'), ('Historical', 'Historical'), ('Diner', 'Diner')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='cost',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1-200', '1-200'), ('201-500', '201-500'), ('501+', '501+')], max_length=100, null=True),
        ),
    ]
