# Generated by Django 5.0.3 on 2024-04-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_rename_annoncement_businessdetails_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='businessowner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
    ]
