# Generated by Django 5.0.3 on 2024-04-06 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_businessdetails_businessowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='businessowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
    ]
