# Generated by Django 5.0.3 on 2024-04-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_businessdetails_businessowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='announcement',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
