# Generated by Django 5.0.3 on 2024-05-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_businessdetails_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
