# Generated by Django 4.1.13 on 2024-05-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_businessdetails_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
