# Generated by Django 5.0.3 on 2024-05-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_businessdetails_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='map',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
