# Generated by Django 4.1.13 on 2024-05-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_alter_businessdetails_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='announcement',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
