# Generated by Django 5.0.3 on 2024-03-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('Leisure', 'Leisure'), ('Educational', 'Educational'), ('Historical', 'Historical'), ('Diner', 'Diner')], default='Leisure', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='category2',
            field=models.CharField(blank=True, choices=[('Leisure', 'Leisure'), ('Educational', 'Educational'), ('Historical', 'Historical'), ('Diner', 'Diner')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='category3',
            field=models.CharField(blank=True, choices=[('Leisure', 'Leisure'), ('Educational', 'Educational'), ('Historical', 'Historical'), ('Diner', 'Diner')], max_length=100, null=True),
        ),
    ]
