# Generated by Django 5.0.3 on 2024-04-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_place_category_alter_place_category2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceid', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
