# Generated by Django 5.0.3 on 2024-08-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_populate_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='places', to='website.media'),
        ),
    ]
