# Generated by Django 5.0.3 on 2024-04-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reference',
        ),
    ]
