# Generated by Django 5.0.3 on 2024-04-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='costmax',
        ),
        migrations.AlterField(
            model_name='place',
            name='cost',
            field=models.DecimalField(choices=[('0', '0'), ('1-200', '1-200'), ('201-500', '201-500'), ('501+', '501+')], decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
