# Generated by Django 5.0.3 on 2024-08-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_place_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='PlaceMedia',
        ),
    ]
