# Generated by Django 5.0.3 on 2024-04-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_place_costmax_alter_place_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='cost',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1-200', '1-200'), ('201-500', '201-500'), ('501+', '501+')], max_length=100, null=True),
        ),
    ]
