# Generated by Django 5.0.3 on 2024-08-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_media_placemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarystate',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
