# Generated by Django 5.0.3 on 2024-05-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_place_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
