# Generated by Django 5.0.3 on 2024-09-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_itinerarystate_budget_itinerarystate_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarystate',
            name='times2',
            field=models.JSONField(default=list),
        ),
    ]
