# Generated by Django 5.0.3 on 2024-09-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_itinerarystate_times2'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarystate',
            name='category',
            field=models.JSONField(default=list),
        ),
    ]
