# Generated by Django 4.1.13 on 2024-05-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='map',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
