# Generated by Django 5.1 on 2024-10-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_itinerarystate_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarystate',
            name='time',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='itinerarystate',
            name='timeclose',
            field=models.JSONField(default=list),
        ),
    ]
