# Generated by Django 4.1.13 on 2024-10-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_itinerarystate_time_itinerarystate_timeclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarystate',
            name='place_count',
            field=models.JSONField(default=list),
        ),
    ]
