# Generated by Django 4.1.13 on 2024-05-23 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0013_itinerarystate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_itinerary', to='website.itinerarystate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_itinerary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
