# Generated by Django 5.1.2 on 2024-10-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_itinerarystate_place_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
