# Generated by Django 4.1.13 on 2024-05-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_favoriteitinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteitinerary',
            name='itinerary_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_itinerary', to='website.itinerarystate'),
        ),
    ]
