# Generated by Django 4.1.13 on 2024-05-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_favoriteitinerary_itinerary_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarystate',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
