# Generated by Django 5.1.2 on 2024-10-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_normaluser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
