# Generated by Django 5.0.3 on 2024-05-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_itinerarystate_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='map',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
