# Generated by Django 4.1.13 on 2024-05-25 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_alter_businessdetails_map'),
        ('website', '0018_alter_place_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.businessdetails'),
        ),
    ]
