# Generated by Django 4.1.13 on 2024-05-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_place_announcement_place_promos_alter_place_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarystate',
            name='place_ids',
            field=models.JSONField(default=list),
        ),
    ]
