# Generated by Django 4.1.13 on 2024-05-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_itinerarystate_place_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarystate',
            name='types',
            field=models.JSONField(default=list),
        ),
    ]
