# Generated by Django 4.1.13 on 2024-05-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_visitor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='user',
        ),
    ]
