# Generated by Django 5.0.3 on 2024-11-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_notification_businessid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='origin',
            field=models.CharField(default='place', max_length=50),
        ),
    ]
