# Generated by Django 5.1.2 on 2024-11-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_notification_businessid'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(max_length=20000),
        ),
    ]
